### ISSUE TITLE
Re-work Parse Workflow Step To be poll based

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-ingest#88]
In testing the clinvar-ingest workflow, we realized that there is a response timeout configured at the cloud run service level. This means that each FastAPI call we make into the service (copy, parse, etc.) will timeout if not complete within the max timeout of 1 hour(3600 sec).

The parse step of the clinvar-ingest workflow will likely take more time than 1 hour to process > 2million VCVs.

I spoke with Kyle about rethinking the parse step to be poll based. It might work as follows:

- Make a call to the parse step in the workflow, exactly as we do today (passing in proper clinvar payload) but have it write a file to a GCP bucket that contains info on the file being processed, and return back to the caller.
- The workflow would then periodically poll the GCP bucket based on the clinvar file name and date, to see if there is either a "success file" or an "error file" that has been generated by the parsing step.

Once either file exists, the workflow can proceed.

**Comment by theferrit32** [comment]
I will move response models like CopyResponse from the initial copy step call, and write it into a 'payload' key in the `STEP-SUCCEEDED.json` file. The initial call to an endpoint like `POST /copy` will return immediately with a `201`. And when it completes, the the `<STEP>-SUCCEEDED.json` file will be a `StatusValue` dict, with a `payload` key added.

e.g. `COPY-SUCCEEDED.json`
```json
{
  "status": "SUCCEEDED",
  "step": "COPY",
  "timestamp": "<timestamp>"
  "payload": {<…CopyResponse> }
}
```

This same structure will be returned by `GET /step_status`

**Comment by theferrit32** [comment]
I have been experimenting with FastAPI's `BackgroundTasks` functionality, and it seems to work perfectly for what we want.
https://fastapi.tiangolo.com/tutorial/background-tasks/

Another option would be to use Python's `asyncio` directly, but this would require more custom code and cleanup, etc. `BackgroundTasks` seems to work the same way but more friendly for simple stuff.

**Comment by theferrit32** [comment]
One extremely important thing to note about BackgroundTasks is related to python's threading issues, and how FastAPI handles sync vs async functions. If the api function is defined as `async`, FastAPI will make the task sent to BackgroundTasks run in the asyncio event loop, which will block the main server thread while it is busy working.

https://stackoverflow.com/a/67601373/2172133

So for example the `/copy` task endpoint, if `async`, will send its task to BackgroundTasks, and that will be executed in the asyncio loop after the `/copy` request returns. When the status check request is then received, it will be blocked, since the main thread of the server is now busy executing the BackgroundTask, and the status check request will not be serviced until that task completes. Which negates the whole purpose of having the long-running task be executed in the background.

As a workaround, I have defined the `/copy` endpoint to just be a regular `def`, not an `async def`. Which, counterintuitively, makes the BackgroundTasks execute the task asynchronously on a separate thread, not blocking the thread which created the task. Since from a `def` function, the BackgroundTask gets executed in a separate threadpool, not in the asyncio loop.

Another workaround if this does not work, is to just create our own threadpool as a global in the `api` module and add tasks to it manually. This is not that complicated and if there's any downsides found in using `def` (not `async def`) or the `BackgroundTasks` from here forward, I think we should move away from it and just use our own thread/process pool. The data passed to the task and returned from it is small, so we `multiprocessing` is also an option.

**Comment by toneillbroad** [comment]
Does seem a little counterintuitive to have to define the task with def and not async def to have it not block. But it is worth trying this out and seeing if it gets us where we need to go.

**Comment by bpblanken** [comment]
A demo like, or something like it, is good for head-wrapping: 

```
def sleep_1(request: Request):
  import time
  time.sleep(5)
  return {}

def sleep_2(request: Request):
   import asyncio
   asyncio.sleep(5)
   return {}

async def sleep_3(request: Request):
  import time
  time.sleep(5)
  return {}

async def sleep_4(request: Request):
   import asyncio
   asyncio.sleep(5)
   return {}

```

**Comment by theferrit32** [comment]
Maybe it's because all the functions down the call stack within the task are not also async, that makes that task in asyncio block the main thread from responding to other requests? I'm not sure, I can play around with a simple example using these functions.

This version of copy using `def` seems to work as intended. It adds the inner task to the BackgroundTasks, returns a response, and the task executes in a way that does not block the uvicorn process from responding to other requests (like status checks) while the task is executing.

https://github.com/clingen-data-model/clinvar-ingest/blob/fbe9a9eb21ec3a0ba6dc7547b0d90130aab48496/clinvar_ingest/api/main.py#L205-L274

**Comment by theferrit32** [comment]
If you change the `def copy` to `async def copy`, other requests are blocked while the task is executing. 

This script runs a copy step on a small file that takes less than a minute to copy, and polls until it completes:

https://github.com/clingen-data-model/clinvar-ingest/blob/issue-88-wf-job-polling/misc/bin/poll-workflow-test.py

**Comment by bpblanken** [comment]
Yeah, I think your understanding (`all the functions down the call stack within the task are not also async`) is exactly correct.  

Basically every standard function in python is blocking by default, so unless we're using async utilities, for example [this](https://docs.python.org/3/library/asyncio-subprocess.html), it's gonna be a bad time.  

At my previous job we basically just set a rule to not use `async` in `FastAPI` because it's way to easy to accidentally put a sync function inside an `async` block and nuke your web server.

**Comment by theferrit32** [comment]
Added a script here: https://github.com/clingen-data-model/clinvar-ingest/blob/issue-88-wf-job-polling/misc/bin/async-request-handling.py

In both scenarios, the inner `task` function is a busy cpu-bound task, and the FastAPI request handler function is `async`. But one inner `task` function is inside a `def` and one is inside a `async def`. The async one blocks the async event loop, which prevents the second request from being responded to until the task finishes (~30 seconds). The sync version of the task does not block the event loop, so the second request returns immediately after it's sent.

**Comment by bpblanken** [comment]
One other potential approach here is to experiment with limited the concurrency of the cloud run job to 1.  So, any request made while a request is in progress would create a new container rather than entering the same container where you have to content with python concurrency nonsense.

**Comment by bpblanken** [comment]
<img width="866" alt="Screenshot 2024-01-30 at 10 11 44 AM" src="https://github.com/clingen-data-model/clinvar-ingest/assets/5325727/e28c5f08-5b1f-41c8-a95c-ffc2e51d8d19">
